export type QuickServiceItem = {
    title: string;
    titleEn: string;
    category: string;
    categoryEn: string;
    description: string;
    descriptionEn: string;
    bullets: string[];
    bulletsEn: string[];
    price: string;
    priceEn: string;
    timeline?: string;
    timelineEn?: string;
};

export const QUICK_SERVICES_DATA: Record<string, QuickServiceItem> = {
    'monitoring-stroiki': {
        title: 'Мониторинг стройки',
        titleEn: 'Construction Progress Audit',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Регулярный 4K видеоконтроль стройплощадок с GPS-привязкой точек. Сравнительные PDF-отчёты для инвесторов и банков без личного выезда на объект.',
        descriptionEn: 'Regular 4K video audits of construction sites with GPS positioning. Comparative PDF reports for investors and banks.',
        bullets: [
            'Облёты по фиксированным GPS-точкам',
            'PDF-отчёт динамики строительства',
            'Передача архива за 24–48 часов',
        ],
        bulletsEn: [
            'Flights across fixed GPS coordinates',
            'PDF construction dynamics report',
            'Raw & edited archive delivery in 24–48h',
        ],
        price: 'от 250 ₾ / выезд',
        priceEn: 'from 250 ₾ / visit',
    },
    'drone-construction': {
        title: 'Мониторинг стройки',
        titleEn: 'Construction Progress Audit',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Регулярный 4K видеоконтроль стройплощадок с GPS-привязкой точек. Сравнительные PDF-отчёты для инвесторов и банков без личного выезда на объект.',
        descriptionEn: 'Regular 4K video audits of construction sites with GPS positioning. Comparative PDF reports for investors and banks.',
        bullets: [
            'Облёты по фиксированным GPS-точкам',
            'PDF-отчёт динамики строительства',
            'Передача архива за 24–48 часов',
        ],
        bulletsEn: [
            'Flights across fixed GPS coordinates',
            'PDF construction dynamics report',
            'Raw & edited archive delivery in 24–48h',
        ],
        price: 'от 350 ₾ / выезд',
        priceEn: 'from 350 ₾ / visit',
    },
    'zemelnye-uchastki': {
        title: 'Земельные участки',
        titleEn: 'Land & Territory Survey',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Аэрофотосъемка границ, ландшафта и окружения земельных участков для инвест-презентаций и быстрой продажи.',
        descriptionEn: 'Aerial photography of boundaries, topography, and surroundings for investment presentations and fast sales.',
        bullets: [
            'Высотные панорамы и границы',
            'Оценка подъездных путей и видов',
            'Фото и видео в 4K',
        ],
        bulletsEn: [
            'High-altitude boundary panoramas',
            'Assessment of road access and view lines',
            'Full 4K photo and video deliverables',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'drone-land-sale': {
        title: 'Земельные участки и девелопмент',
        titleEn: 'Land Plot Sales & Development',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Аэрофотосъемка границ, ландшафта и окружения земельных участков для инвест-презентаций и быстрой продажи.',
        descriptionEn: 'Aerial photography of boundaries, topography, and surroundings for investment presentations and fast sales.',
        bullets: [
            'Высотные панорамы и границы участка',
            'Оценка подъездных путей, коммуникаций и рельефа',
            'Фото и видео в 4K HDR для презентаций',
        ],
        bulletsEn: [
            'High-altitude plot panoramas and borders',
            'Access road, utilities, and topography assessment',
            '4K HDR photo & video for investor pitches',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'inspekciya-fasadov': {
        title: 'Инспекция фасадов и кровли',
        titleEn: 'Facade & Roof Drone Inspection',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Детальная фото- и видеофиксация фасадов, кровли и высотных конструкций без лесов и альпинистов.',
        descriptionEn: 'Detailed photo and video inspection of facades, roofing, and high-altitude structures without scaffolding.',
        bullets: [
            'Безопасный осмотр скрытых дефектов',
            'Высокая детализация трещин и швов',
            'Готовые материалы за 24ч',
        ],
        bulletsEn: [
            'Safe inspection of hidden structural defects',
            'High-res zoom on cracks, seams, and joints',
            'Deliverables ready within 24h',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'drone-facades': {
        title: 'Инспекция фасадов и крыш',
        titleEn: 'Facade & Roof Audit',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Детальная фото- и видеофиксация фасадов, кровли и высотных конструкций без лесов и альпинистов.',
        descriptionEn: 'Detailed photo and video inspection of facades, roofing, and high-altitude structures without scaffolding.',
        bullets: [
            'Безопасный осмотр высотных конструкций',
            'Высокая детализация дефектов в 4K',
            'Готовые материалы за 24 часа',
        ],
        bulletsEn: [
            'Safe inspection of high-altitude structures',
            'High-res 4K documentation of defects',
            'Ready materials delivered in 24h',
        ],
        price: 'от 400 ₾',
        priceEn: 'from 400 ₾',
    },
    'drone-facade': {
        title: 'Инспекция фасадов и крыш',
        titleEn: 'Facade & Roof Audit',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Детальная фото- и видеофиксация фасадов, кровли и высотных конструкций без лесов и альпинистов.',
        descriptionEn: 'Detailed photo and video inspection of facades, roofing, and high-altitude structures without scaffolding.',
        bullets: [
            'Безопасный осмотр высотных конструкций',
            'Высокая детализация дефектов в 4K',
            'Готовые материалы за 24 часа',
        ],
        bulletsEn: [
            'Safe inspection of high-altitude structures',
            'High-res 4K documentation of defects',
            'Ready materials delivered in 24h',
        ],
        price: 'от 400 ₾',
        priceEn: 'from 400 ₾',
    },
    'regulyarnye-aerootchety': {
        title: 'Регулярные аэроотчёты',
        titleEn: 'Regular Aerial Video Reports',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Ежемесячный или сезонный видеоархив для девелоперов и фондов.',
        descriptionEn: 'Monthly or seasonal video archive for developers and investment funds.',
        bullets: [
            'Сравнение прогресса месяц к месяцу',
            'Облачный структурированный архив',
            'Таймлапс строительства',
        ],
        bulletsEn: [
            'Month-over-month progress comparison',
            'Structured cloud asset storage',
            'Construction time-lapse sequences',
        ],
        price: 'от 900 ₾ / мес',
        priceEn: 'from 900 ₾ / mo',
    },
    'drone-reporting': {
        title: 'Регулярные аэроотчёты',
        titleEn: 'Regular Aerial Video Reports',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Ежемесячный или сезонный видеоархив для девелоперов и фондов.',
        descriptionEn: 'Monthly or seasonal video archive for developers and investment funds.',
        bullets: [
            'Сравнение прогресса месяц к месяцу',
            'Облачный структурированный архив',
            'Таймлапс строительства',
        ],
        bulletsEn: [
            'Month-over-month progress comparison',
            'Structured cloud asset storage',
            'Construction time-lapse sequences',
        ],
        price: 'от 900 ₾ / мес',
        priceEn: 'from 900 ₾ / mo',
    },
    'fpv-semka': {
        title: 'FPV-съёмка One-Take',
        titleEn: 'FPV Cinema Flythrough',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Динамичный непрерывный пролет FPV-дрона сквозь интерьеры, залы, террасы и арки для создания вау-эффекта в соцсетях.',
        descriptionEn: 'Dynamic continuous FPV drone flight through interiors, halls, and outdoor terraces for viral social media impact.',
        bullets: [
            'Единый бесшовный пролет One-Take',
            'Показ атмосферы и маршрута гостя',
            'Стабилизация и цветокоррекция',
        ],
        bulletsEn: [
            'Seamless One-Take continuous flight',
            'Showcases atmosphere and guest path',
            'RockSteady stabilization & color grading',
        ],
        price: 'от 350 ₾',
        priceEn: 'from 350 ₾',
    },
    'fpv-cinema': {
        title: 'FPV Cinema',
        titleEn: 'FPV Cinema',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Динамичный непрерывный пролет FPV-дрона сквозь интерьеры, залы, террасы и арки для создания вау-эффекта в соцсетях.',
        descriptionEn: 'Dynamic continuous FPV drone flight through interiors, halls, and outdoor terraces for viral social media impact.',
        bullets: [
            'Единый бесшовный пролет One-Take',
            'Показ атмосферы и маршрута гостя',
            'Стабилизация и цветокоррекция',
        ],
        bulletsEn: [
            'Seamless One-Take continuous flight',
            'Showcases atmosphere and guest path',
            'RockSteady stabilization & color grading',
        ],
        price: 'от 350 ₾',
        priceEn: 'from 350 ₾',
    },
    'drone-auto': {
        title: 'Автобизнес в движении',
        titleEn: 'Automotive in Motion',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Динамичное слежение за автомобилями на горных дорогах, треках и серпантинах Грузии на скорости до 100 км/ч.',
        descriptionEn: 'Dynamic car chase tracking on mountain passes and tracks across Georgia at speeds up to 100 km/h.',
        bullets: [
            'FPV трекинг на высоких скоростях',
            'Кинематографичные ракурсы экстерьера',
            'Цветокоррекция под рекламные стандарты',
        ],
        bulletsEn: [
            'High-speed FPV chase cam',
            'Cinematic exterior automotive angles',
            'Commercial-grade color grading',
        ],
        price: 'от 300 ₾',
        priceEn: 'from 300 ₾',
    },
    'drone-solar': {
        title: 'Солнечные электростанции',
        titleEn: 'Solar Farm Aerial Inspection',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Аэроинспекция фотоэлектрических панелей, инверторов и кабельных трасс с фиксацией дефектов.',
        descriptionEn: 'Aerial audit of photovoltaic panels, inverters, and cabling to detect efficiency drops.',
        bullets: [
            'Быстрое покрытие больших площадей',
            'Высокая детализация поверхности панелей',
            'Формирование отчёта для инженеров',
        ],
        bulletsEn: [
            'Fast coverage of large solar farms',
            'High-resolution panel surface inspection',
            'Technical engineering report delivery',
        ],
        price: 'от 450 ₾',
        priceEn: 'from 450 ₾',
    },
    'drone-warehouses': {
        title: 'Логистические комплексы и склады',
        titleEn: 'Logistics & Warehouse Audit',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Съёмка территории логистических парков, подъездных путей для фур, рамп и складских площадей.',
        descriptionEn: 'Drone overview of logistics hubs, freight access routes, loading ramps, and warehouse yards.',
        bullets: [
            'Масштаб территории и транспортная доступность',
            'Обзор кровли и складских ангаров',
            'Материалы для арендаторов и инвесторов',
        ],
        bulletsEn: [
            'Yard scale and highway transport access',
            'Roof and hangar condition overview',
            'Materials for tenants and investors',
        ],
        price: 'от 400 ₾',
        priceEn: 'from 400 ₾',
    },
    'drone-wine': {
        title: 'Винодельни и шато Кахетии',
        titleEn: 'Wineries & Vineyards in Kakheti',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Атмосферная съёмка виноградников, старинных погребов (марани), дегустационных залов и шато.',
        descriptionEn: 'Atmospheric drone filming of vineyards, traditional marani cellars, tasting rooms, and estates.',
        bullets: [
            'Панорамы виноградников на рассвете/закате',
            'FPV пролёт через погреба и шато',
            'Контент для винного туризма и экспорта',
        ],
        bulletsEn: [
            'Sunrise and sunset vineyard panoramas',
            'FPV flythrough of cellars and chateaus',
            'Visuals for wine tourism & export sales',
        ],
        price: 'от 450 ₾',
        priceEn: 'from 450 ₾',
    },
    'drone-sport': {
        title: 'Спортивные события и экстрим',
        titleEn: 'Sports & Action Events',
        category: 'Аэросъёмка',
        categoryEn: 'Aerial Filming',
        description: 'Аэросъёмка соревнований, марафонов, горнолыжных спусков в Гудаури и активного отдыха.',
        descriptionEn: 'Aerial filming of sports events, marathons, ski slopes in Gudauri, and outdoor adventures.',
        bullets: [
            'Динамичное слежение за спортсменами',
            'Эпичные горные ракурсы в 4K 60fps',
            'Быстрый монтаж хайлайтов для соцсетей',
        ],
        bulletsEn: [
            'Dynamic tracking of athletes in action',
            'Epic 4K 60fps mountain perspectives',
            'Fast-turnaround event highlight reels',
        ],
        price: 'от 350 ₾',
        priceEn: 'from 350 ₾',
    },
    'tour-restaurants': {
        title: '360° туры ресторанов и залов',
        titleEn: '360° Tours for Restaurants & Bars',
        category: '360° туры',
        categoryEn: '360° Virtual Tours',
        description: 'Интерактивный 8K тур по залам ресторана, банкетным зонам и террасе для бронирования столов и мероприятий.',
        descriptionEn: 'Interactive 8K virtual walkthrough of dining rooms, banquet areas, and outdoor terraces.',
        bullets: [
            'Интеграция с Google Maps и Яндекс Картами',
            'Возможность выбора конкретного столика',
            'Работает на любых смартфонах без установки приложений',
        ],
        bulletsEn: [
            'Integrated into Google Maps Street View',
            'Virtual table and banquet area selection',
            'Runs seamlessly on any smartphone without apps',
        ],
        price: 'от 300 ₾',
        priceEn: 'from 300 ₾',
    },
    'tour-clinics': {
        title: '360° туры клиник и медцентров',
        titleEn: '360° Tours for Clinics & Medical',
        category: '360° туры',
        categoryEn: '360° Virtual Tours',
        description: 'Виртуальная демонстрация стерильности, современных кабинетов и премиального оборудования для роста доверия пациентов.',
        descriptionEn: 'Virtual showcase of clinical cleanliness, surgery rooms, and modern medical equipment.',
        bullets: [
            'Эффект присутствия до первого визита',
            'Показ диагностического оборудования',
            'Интеграция на сайт клиники и карты',
        ],
        bulletsEn: [
            'Patient trust before the first appointment',
            'Showcasing high-end diagnostic equipment',
            'Embedding on website and map listings',
        ],
        price: 'от 350 ₾',
        priceEn: 'from 350 ₾',
    },
    'tour-auto': {
        title: '360° виртуальные автосалоны',
        titleEn: '360° Virtual Auto Showrooms',
        category: '360° туры',
        categoryEn: '360° Virtual Tours',
        description: 'Интерактивный осмотр модельного ряда автосалона и интерьера премиальных автомобилей.',
        descriptionEn: 'Interactive walkthrough of car dealerships and 360° interior scans of premium vehicles.',
        bullets: [
            'Круговой обзор экстерьера и салона авто',
            'Интерактивные точки с характеристиками',
            'Прямая ссылка для отправки клиентам в мессенджеры',
        ],
        bulletsEn: [
            '360° interior and exterior vehicle inspection',
            'Interactive spec points & option highlights',
            'Instant sharable link for WhatsApp & CRM',
        ],
        price: 'от 300 ₾',
        priceEn: 'from 300 ₾',
    },
    'tour-business': {
        title: '360° туры коворкингов и офисов',
        titleEn: '360° Coworking & Office Tours',
        category: '360° туры',
        categoryEn: '360° Virtual Tours',
        description: 'Презентация рабочих мест, переговорных комнат и инфраструктуры бизнес-центров для привлечения резидентов.',
        descriptionEn: 'Virtual walkthrough of flex offices, meeting rooms, and amenities to attract corporate tenants.',
        bullets: [
            'Навигация по этажам и кабинетам',
            'Интерактивные планировки с ценами',
            'Рост конверсии заявок на аренду',
        ],
        bulletsEn: [
            'Floor-to-floor virtual spatial navigation',
            'Interactive office floorplans with prices',
            'Increased leasing inquiry conversion',
        ],
        price: 'от 350 ₾',
        priceEn: 'from 350 ₾',
    },
    'tour-tourism': {
        title: '360° панорамы достопримечательностей',
        titleEn: '360° Travel & Landmark Tours',
        category: '360° туры',
        categoryEn: '360° Virtual Tours',
        description: 'Сферические 8K панорамы исторических крепостей, горных перевалов и туристических маршрутов.',
        descriptionEn: 'Spherical 8K panoramas of historical fortresses, mountain passes, and iconic Georgian destinations.',
        bullets: [
            'Публикация в Google Street View',
            'Поддержка VR-очков и интерактивных гидов',
            'Встраивание в туристические порталы',
        ],
        bulletsEn: [
            'Google Street View official publishing',
            'VR headset and interactive guide support',
            'Embeddable in travel booking portals',
        ],
        price: 'от 300 ₾',
        priceEn: 'from 300 ₾',
    },
    'reels-restaurant': {
        title: 'Reels для ресторанов и баров',
        titleEn: 'Restaurant & Food Reels',
        category: 'Reels & Promo',
        categoryEn: 'Reels & Promo',
        description: 'Сочные вертикальные видео подачи блюд, барного искусства, вечеринок и атмосферы заведения.',
        descriptionEn: 'Mouth-watering vertical videos of dish plating, mixology, kitchen craft, and vibrant nightlife.',
        bullets: [
            'Макросъёмка текстуры и подачи блюд',
            'Трендовый динамичный саунд-дизайн',
            'Формат 9:16 под Instagram и TikTok',
        ],
        bulletsEn: [
            'Macro food texture & plating cinematography',
            'Trending sound design & rhythm sync',
            '9:16 vertical format for Instagram & TikTok',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'reels-business': {
        title: 'Reels для бизнеса и экспертов',
        titleEn: 'Business & Personal Brand Reels',
        category: 'Reels & Promo',
        categoryEn: 'Reels & Promo',
        description: 'Экспертные ролики, интервью фаундеров, демонстрация процессов и упаковка личного бренда.',
        descriptionEn: 'Expert talking-head videos, founder stories, workflow demos, and personal branding content.',
        bullets: [
            'Запись звука на микрофоны DJI Mic 2',
            'Анимированные субтитры и акценты',
            'Сценарий и режиссура на съёмке',
        ],
        bulletsEn: [
            'Studio-grade audio with DJI Mic 2 systems',
            'Dynamic kinetic captions and visual hooks',
            'On-set scripting and directing support',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'reels-auto': {
        title: 'Reels для автобизнеса и детейлинга',
        titleEn: 'Automotive & Detailing Reels',
        category: 'Reels & Promo',
        categoryEn: 'Reels & Promo',
        description: 'Эффектные ролики до/после полировки, оклейки плёнкой, звуки выхлопа и обзоры авто в продаже.',
        descriptionEn: 'High-impact before/after detailing reels, wrap showcases, exhaust notes, and car reviews.',
        bullets: [
            'ASMR звук полировки и работы мотора',
            'Динамичные переходы и акценты на деталях',
            'Пакетный монтаж от 3 роликов за съёмку',
        ],
        bulletsEn: [
            'ASMR audio of engine revs & detailing craft',
            'High-energy transitions & macro finish focus',
            'Packaged editing from 3 clips per session',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'reels-clinic': {
        title: 'Reels для клиник и врачей',
        titleEn: 'Medical & Doctor Expert Reels',
        category: 'Reels & Promo',
        categoryEn: 'Reels & Promo',
        description: 'Экспертные ответы на вопросы пациентов, развенчание мифов, демонстрация заботы и технологий.',
        descriptionEn: 'Doctor Q&A formats, myth-busting health reels, care demonstrations, and technology showcases.',
        bullets: [
            'Тактичная съёмка в медицинских интерьерах',
            'Крупные читаемые субтитры для вовлечения',
            'Рост доверия и записей на первичный приём',
        ],
        bulletsEn: [
            'Discrete clinical cinematography',
            'High-legibility animated subtitles',
            'Proven to increase first-visit booking rates',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'reels-tourism': {
        title: 'Reels тревел-впечатлений',
        titleEn: 'Travel Experience Reels',
        category: 'Reels & Promo',
        categoryEn: 'Reels & Promo',
        description: 'Яркие эмоции туристов, аутентичные грузинские застолья, горные панорамы и эксклюзивные маршруты.',
        descriptionEn: 'Real traveler emotions, authentic Georgian supra feasts, mountain vistas, and bespoke itineraries.',
        bullets: [
            'Эмоциональный монтаж с грузинским колоритом',
            'Оптимизация под алгоритмы рекомендаций',
            'Быстрая передача готовых роликов',
        ],
        bulletsEn: [
            'High-emotion editing with local Georgian vibe',
            'Algorithmic hook optimization for reach',
            'Rapid turnaround for live campaign rollouts',
        ],
        price: 'от 250 ₾',
        priceEn: 'from 250 ₾',
    },
    'ai-brand': {
        title: 'AI Бренд-визуализации',
        titleEn: 'AI Brand & Commercial Visuals',
        category: 'AI-контент',
        categoryEn: 'AI Content',
        description: 'Генерация рекламных постеров, 3D-концептов продуктов и студийных визуалов без аренды павильона.',
        descriptionEn: 'Generative commercial posters, 3D product concepts, and studio imagery without set rentals.',
        bullets: [
            'Разрешение до 8K для наружной рекламы и печати',
            'Сохранение айдентики и цветов бренда',
            'Готовность первых концептов за 12 часов',
        ],
        bulletsEn: [
            'Up to 8K resolution for billboards & print',
            'Strict adherence to brand guide & colors',
            'Initial design concepts delivered in 12h',
        ],
        price: 'от 200 ₾',
        priceEn: 'from 200 ₾',
    },
    'ai-menu-delivery': {
        title: 'AI Меню и фуд-карточки',
        titleEn: 'AI Food & Delivery Menus',
        category: 'AI-контент',
        categoryEn: 'AI Content',
        description: 'Создание аппетитных превью блюд для сервисов доставки Wolt / Glovo и цифровых меню по QR-коду.',
        descriptionEn: 'High-conversion appetizing food imagery for Wolt / Glovo delivery apps and digital QR menus.',
        bullets: [
            'Увеличение кликабельности позиций на 25–40%',
            'Единый премиальный стиль подачи всех блюд',
            'Быстрая упаковка меню любого объёма',
        ],
        bulletsEn: [
            '25–40% higher click-through on delivery apps',
            'Unified luxury plating aesthetics',
            'Fast packaging for menus of any scale',
        ],
        price: 'от 180 ₾',
        priceEn: 'from 180 ₾',
    },
    'ai-auto': {
        title: 'AI Студийный фон для автокаталогов',
        titleEn: 'AI Virtual Studio for Cars',
        category: 'AI-контент',
        categoryEn: 'AI Content',
        description: 'Замена уличных фонов авто на фотореалистичные премиальные студии для сайтов дилеров и MyAuto.ge.',
        descriptionEn: 'Replacing street backgrounds with photorealistic luxury lighting studios for dealer inventory & MyAuto.ge.',
        bullets: [
            'Премиальный вид каждого автомобиля в каталоге',
            'Обработка сотен фото за считанные часы',
            'Рост доверия и звонков от покупателей',
        ],
        bulletsEn: [
            'Showroom-grade look for every inventory unit',
            'Batch processing hundreds of photos in hours',
            'Higher buyer confidence and incoming calls',
        ],
        price: 'от 180 ₾',
        priceEn: 'from 180 ₾',
    },
};

export function getQuickServiceData(keyOrId: string, lang: 'ru' | 'en' = 'ru') {
    const isEn = lang === 'en';
    const item = QUICK_SERVICES_DATA[keyOrId];
    if (!item) {
        return {
            title: isEn ? 'Custom Production Solution' : 'Индивидуальная задача',
            category: isEn ? 'Production' : 'Услуги',
            description: isEn
                ? 'Tell us about your project goals and requirements. We will prepare an exact estimate and filming route in 2 hours.'
                : 'Расскажите о вашей задаче. Мы подготовим точную смету, сценарий и план съёмки за 2 часа.',
            bullets: isEn
                ? ['4K HDR quality filming', 'Licensed DJI equipment', 'Official B2B contract & invoices']
                : ['Съёмка в 4K HDR качестве', 'Оборудование DJI и профессиональный звук', 'Официальный договор и закрывающие акты'],
            price: isEn ? 'from 250 ₾' : 'от 250 ₾',
        };
    }

    return {
        title: isEn ? item.titleEn : item.title,
        category: isEn ? item.categoryEn : item.category,
        description: isEn ? item.descriptionEn : item.description,
        bullets: isEn ? item.bulletsEn : item.bullets,
        price: isEn ? item.priceEn : item.price,
    };
}
