export type DroneServiceItem = {
    id: number;
    order: number;
    slug: string;
    title: string;
    category: string;
    description: string;
    price: string;
    image: string;
    primaryHref: string;
    primaryCtaLabel?: string;
    secondaryHref?: string;
    secondaryCtaLabel?: string;
    tag?: string;
    featured?: boolean;
};

export const droneServiceItems: DroneServiceItem[] = [
    {
        id: 1,
        order: 1,
        slug: 'nedvizhimost',
        title: 'Недвижимость',
        category: 'РИЕЛТОРЫ · ЗАСТРОЙЩИКИ · ИНВЕСТОРЫ',
        description: 'Аэрофото и видео для карточек объектов и инвесторов. Объекты с воздушной съёмкой продаются на 68% быстрее.',
        price: '4K · GPS · НЕДВИЖИМОСТЬ',
        image: '/media/drone-service/real-estate-1.png',
        primaryHref: '/drone-real-estate',
        secondaryHref: '#service-nedvizhimost',
        secondaryCtaLabel: 'На странице',
        tag: 'SALE',
    },
    {
        id: 2,
        order: 2,
        slug: 'monitoring-stroiki',
        title: 'Мониторинг стройки',
        category: 'ДЕВЕЛОПЕРЫ · БАНКИ · ПОДРЯДЧИКИ',
        description: 'Стройка идёт — но как на самом деле? Еженедельный облёт фиксирует этапы и даёт инвестору честную картину без выезда.',
        price: '4K · GPS · ОТЧЁТЫ',
        image: '/media/drone-service/construction-monitoring-1.png',
        primaryHref: '/drone-construction-monitoring',
        secondaryHref: '#service-monitoring-stroiki',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 3,
        order: 3,
        slug: 'fpv-semka',
        title: 'FPV Съёмка',
        category: 'СКЛАДЫ · ЦЕХА · КОММЕРЧЕСКАЯ НЕДВИЖИМОСТЬ',
        description: 'Показываем коммерческое пространство изнутри одним кадром — от входа до последней зоны. Инвестор или арендатор понимает объект ещё до встречи.',
        price: '4K · FPV · ДИНАМИКА',
        image: '/media/drone-service/fpv-2.png',
        primaryHref: '/drone-fpv-cinema',
        secondaryHref: '#service-fpv-semka',
        secondaryCtaLabel: 'На странице',
        tag: 'HOT',
        featured: true,
    },
    {
        id: 4,
        order: 4,
        slug: 'oteli-kurorty',
        title: 'Отели & Курорты',
        category: 'ОТЕЛИ · АПАРТ-ОТЕЛИ · КУРОРТЫ',
        description: 'Гость бронирует глазами. Снимаем отель, террасы и виды так, чтобы страница на Booking работала сама.',
        price: '4K · АТМОСФЕРА · ПРОМО',
        image: '/media/drone-service/hotels-resorts-5.png',
        primaryHref: '/drone-hotels-tourism',
        secondaryHref: '#service-oteli-kurorty',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 5,
        order: 5,
        slug: 'restorany',
        title: 'Рестораны',
        category: 'ВЕРАНДЫ · ЛОКАЦИИ · АТМОСФЕРА',
        description: 'Терраса на крыше, двор с зеленью, расположение в квартале — всё это видно с воздуха. Гость понимает куда едет ещё до того как забронировал столик.',
        price: '4K · REELS · АТМОСФЕРА',
        image: '/media/drone-service/restaurants-3.png',
        primaryHref: '/drone-services/drone-restaurants',
        secondaryHref: '#service-restorany',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 6,
        order: 6,
        slug: 'turizm',
        title: 'Туризм и локации',
        category: 'ПРИРОДА · МАРШРУТЫ · ГЛЭМПИНГИ',
        description: 'Горы, замки и каньоны Грузии — снимаем локации с воздуха для туроператоров, отелей и личного бренда.',
        price: '4K · КИНО · МУЗЫКА',
        image: '/media/drone-service/tourism-6.png',
        primaryHref: '/drone-hotels-tourism',
        secondaryHref: '#service-turizm',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 7,
        order: 7,
        slug: 'meropriyatiya',
        title: 'Мероприятия',
        category: 'ИВЕНТЫ · ОТКРЫТИЯ · СПОРТ',
        description: 'С земли — толпа. С воздуха — масштаб, энергия и атмосфера события. Готовое видео за 48 часов.',
        price: '4K · МУЛЬТИКАМ · МОНТАЖ',
        image: '/media/drone-service/events-1.png',
        primaryHref: '/drone-weddings-events',
        secondaryHref: '#service-meropriyatiya',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 8,
        order: 8,
        slug: 'inspekciya-obektov',
        title: 'Инспекция объектов',
        category: 'ФАСАДЫ · КРЫШИ · ПРОМЗДАНИЯ',
        description: 'Есть объект, который нужно осмотреть — снаружи, сверху или в труднодоступных зонах. Дрон фиксирует каждую зону безопасно, без остановки работы.',
        price: '4K · ИНСПЕКЦИЯ · ОТЧЁТ',
        image: '/media/drone-service/object-inspection-from-territory-1.png',
        primaryHref: '/drone-object-inspection',
        secondaryHref: '#service-inspekciya-obektov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 9,
        order: 9,
        slug: 'kontrol-territorii',
        title: 'Мониторинг территорий',
        category: 'ПОСЕЛКИ · ПАРКИ · КАРЬЕРЫ',
        description: 'Крупный объект сложно контролировать с земли. Еженедельный облёт с GPS-привязкой даёт полную карту изменений без выезда на место.',
        price: '4K · GPS · ОТЧЁТЫ',
        image: '/media/drone-service/territory-monitoring-2.png',
        primaryHref: '/drone-services/drone-territory',
        secondaryHref: '#service-kontrol-territorii',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 10,
        order: 10,
        slug: 'interiery-sklady',
        title: 'Съёмка интерьеров и складов',
        category: 'СКЛАДЫ · ШОУРУМЫ · ЦЕХА',
        description: 'Дрон пролетает сквозь стеллажи, проёмы и цеха — туда, куда камера на штативе не попадёт. Один дубль — и пространство читается.',
        price: '4K · FPV · ИНТЕРЬЕР',
        image: '/media/drone-service/interiors-warehouses-1.png',
        // TODO(10.04.2026): route is a thin alias page with redirect; keep href active, consider linking directly to the canonical L3 URL.
        primaryHref: '/drone-warehouses',
        secondaryHref: '#service-interiery-sklady',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 11,
        order: 11,
        slug: 'sport-kompleksy',
        title: 'Спорт комплексы',
        category: 'ПОЛЯ · АРЕНЫ · ТЕННИСНЫЕ КОРТЫ',
        description: 'Арена выглядит масштабно только с воздуха. Снимаем поля, трибуны и инфраструктуру — для сайта, инвесторов и соцсетей.',
        price: '4K · 60FPS · СПОРТ',
        image: '/media/drone-service/sport-complex-1.png',
        primaryHref: '/drone-services/drone-sport',
        secondaryHref: '#service-sport-kompleksy',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 12,
        order: 12,
        slug: 'reklama-brand-video',
        title: 'Реклама и бренд видео',
        category: 'БРЕНДЫ · КОРПОРАТИВЫ · ПРОДУКТЫ',
        description: 'Воздушные кадры, сценарий и монтаж в одном проекте. Видео, которое работает в рекламе, на сайте и в соцсетях.',
        price: '4K · СЦЕНАРИЙ · МОНТАЖ',
        image: '/media/drone-service/brand-video-1.png',
        // TODO(10.04.2026): page.tsx is a thin server entrypoint that delegates to client page; keep href active and monitor content parity.
        primaryHref: '/drone-services/drone-brand-video',
        secondaryHref: '#service-reklama-brand-video',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 13,
        order: 13,
        slug: 'aerosyemka-dlya-avto-i-avtosalonov',
        title: 'Автосалоны и шоурумы',
        category: 'АВТО · АВТОСАЛОНЫ · АВТОПЛОЩАДКИ',
        description: 'Покупатель выбирает глазами. Показываем весь ассортимент, площадку и инфраструктуру салона одним пролётом.',
        price: '4K · АВТО · СЪЁМКА',
        image: '/media/drone-service/auto-showroom-1.png',
        primaryHref: '/drone-services/drone-auto',
        secondaryHref: '#service-aerosyemka-dlya-avto-i-avtosalonov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 14,
        order: 14,
        slug: 'agro-i-vinodelie',
        title: 'Агро и виноделие',
        category: 'ВИНОГРАДНИКИ · САДЫ · ВИНОДЕЛЬНИ',
        description: 'Грузинское вино начинается с лозы. Аэросъёмка виноградников и хозяйств — для мониторинга урожая и промо бренда.',
        price: '4K · АГРО · МОНИТОРИНГ',
        image: '/media/drone-service/agro-wine-1.png',
        primaryHref: '/drone-services/drone-wine',
        secondaryHref: '#service-agro-i-vinodelie',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 15,
        order: 15,
        slug: 'zemelnye-uchastki',
        title: 'Земельные участки',
        category: 'УЧАСТКИ · РЕЛЬЕФ · ПОДЪЕЗДЫ',
        description: 'Границы, рельеф, окружение и доступность — всё в одном облёте. Продаёт быстрее любого описания.',
        price: '4K · ЗЕМЛЯ · ОБЗОР',
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
        primaryHref: '/drone-services/drone-land-sale',
        secondaryHref: '#service-zemelnye-uchastki',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 16,
        order: 16,
        slug: 'inspekciya-krysh',
        title: 'Инспекция крыш',
        category: 'КРОВЛЯ · ДЕФЕКТЫ · ДОСТУП',
        description: 'Инспекция кровли без лесов и подъёмников. Видеозапись каждой зоны — ваши специалисты смотрят сами.',
        price: '4K · КРОВЛЯ · ИНСПЕКЦИЯ',
        image: '/media/drone-service/roof-inspection-1.png',
        primaryHref: '/drone-services/drone-facade',
        secondaryHref: '#service-inspekciya-krysh',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 17,
        order: 17,
        slug: 'inspekciya-fasadov',
        title: 'Инспекция фасадов',
        category: 'ФАСАДЫ · ШВЫ · ВЫСОТА',
        description: 'Полный облёт фасада с видео — без лесов, без риска для персонала и без остановки объекта. Материал передаётся вашим специалистам.',
        price: '4K · ФАСАД · ИНСПЕКЦИЯ',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80',
        primaryHref: '/drone-services/drone-facade',
        secondaryHref: '#service-inspekciya-fasadov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 18,
        order: 18,
        slug: 'inspekciya-solnechnyh-paneley',
        title: 'Инспекция солнечных панелей',
        category: 'ПАНЕЛИ · КРОВЛЯ · ОСМОТР',
        description: 'Грязь и повреждения снижают выработку панелей до 30%. Один облёт с видео — и у вашего инженера есть полная картина без подъёма на крышу.',
        price: '4K · ПАНЕЛИ · КРОВЛЯ',
        image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80',
        primaryHref: '/drone-services/drone-solar',
        secondaryHref: '#service-inspekciya-solnechnyh-paneley',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 19,
        order: 19,
        slug: 'regulyarnye-aerootchety',
        title: 'Регулярные аэроотчёты',
        category: 'ОТЧЁТЫ · ДИНАМИКА · КОНТРОЛЬ',
        description: 'Еженедельные облёты с GPS-отчётом — инвестор видит динамику объекта без выезда на стройку.',
        price: '4K · ОТЧЁТЫ · GPS',
        image: '/media/drone-service/reporting-1.png',
        primaryHref: '/drone-services/drone-reporting',
        secondaryHref: '#service-regulyarnye-aerootchety',
        secondaryCtaLabel: 'На странице',
    },
];
