export type DroneServiceItem = {
    id: number;
    order: number;
    slug: string;
    title: string;
    category: string;
    description: string;
    price: string;
    specs?: string;
    image: string;
    primaryHref: string;
    primaryCtaLabel?: string;
    secondaryHref?: string;
    secondaryCtaLabel?: string;
    tag?: string;
    featured?: boolean;
};

export const DRONE_OPEN_SERVICE_SLUGS = ['nedvizhimost', 'oteli-kurorty', 'restorany'] as const;

const DRONE_OPEN_SERVICE_PRIORITY: Record<string, number> = {
    nedvizhimost: 0,
    'oteli-kurorty': 1,
    restorany: 2,
};

export const getDroneServiceSortRank = (item: DroneServiceItem) => {
    const priority = DRONE_OPEN_SERVICE_PRIORITY[item.slug];
    if (priority !== undefined) return priority;
    return 100 + (item.order ?? item.id);
};

export const droneServiceItems: DroneServiceItem[] = [
    {
        id: 1,
        order: 1,
        slug: 'nedvizhimost',
        title: 'Недвижимость',
        category: 'РИЕЛТОРЫ · ЗАСТРОЙЩИКИ · ПРОДАЖИ',
        description: 'Аэрофото и видео для карточек объектов и инвесторов. 94% больше просмотров получают объявления с аэрофото — по данным HomeJab.',
        price: 'от 200 ₾',
        specs: '4K · MYHOME.GE · SS.GE',
        image: '/media/drone-service/real-estate-1.png',
        primaryHref: '/drone-services/drone-real-estate',
        secondaryHref: '#service-nedvizhimost',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 4,
        order: 2,
        slug: 'oteli-kurorty',
        title: 'Отели, курорты и туризм',
        category: 'ОТЕЛИ · ТУРОПЕРАТОРЫ · ГИДЫ · ЛОКАЦИИ',
        description: 'Гость выбирает глазами. Снимаем отели, глэмпинги, видовые маршруты и природные локации Грузии для туроператоров, гидов и Booking — контент, который продаёт атмосферу отдыха.',
        price: 'от 200 ₾',
        specs: '4K · АТМОСФЕРА · ПРОМО',
        image: '/media/drone-service/hotels-resorts-5.png',
        primaryHref: '/drone-hotels-tourism',
        secondaryHref: '#service-oteli-kurorty',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 5,
        order: 3,
        slug: 'restorany',
        title: 'Рестораны',
        category: 'ВЕРАНДЫ · ЛОКАЦИИ · АТМОСФЕРА',
        description: 'Терраса на крыше, двор с зеленью, расположение в квартале — всё это видно с воздуха. Гость понимает куда едет ещё до того как забронировал столик.',
        price: 'от 200 ₾',
        specs: '4K · REELS · STORIES',
        image: '/media/drone-service/restaurants-3.png',
        primaryHref: '/drone-services/drone-restaurants',
        secondaryHref: '#service-restorany',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 3,
        order: 4,
        slug: 'fpv-semka',
        title: 'FPV Съёмка',
        category: 'СКЛАДЫ · ЦЕХА · ЛОГИСТИКА',
        description: 'Показываем коммерческое пространство изнутри одним кадром — от входа до последней зоны. Инвестор или арендатор понимает объект ещё до встречи.',
        price: 'от 300 ₾',
        specs: '4K · ПРОЛЁТ ВНУТРИ',
        image: '/media/drone-service/fpv-2.png',
        primaryHref: '#contact',
        secondaryHref: '#service-fpv-semka',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 2,
        order: 5,
        slug: 'monitoring-stroiki',
        title: 'Мониторинг стройки',
        category: 'ДЕВЕЛОПЕРЫ · БАНКИ · ПОДРЯДЧИКИ',
        description: 'Стройка идёт — но как на самом деле? Еженедельный облёт фиксирует этапы и даёт инвестору честную картину без выезда.',
        price: 'от 200 ₾',
        specs: '4K · GPS · ОТЧЁТЫ',
        image: '/media/drone-service/construction-monitoring-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-monitoring-stroiki',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 7,
        order: 11,
        slug: 'meropriyatiya',
        title: 'Мероприятия',
        category: 'ИВЕНТЫ · ОТКРЫТИЯ · СВАДЬБЫ',
        description: 'С земли — толпа. С воздуха — масштаб, энергия и атмосфера события. Готовое видео за 48 часов.',
        price: 'от 200 ₾',
        specs: '4K · СПОРТ · СОБЫТИЯ',
        image: '/media/drone-service/events-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-meropriyatiya',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 8,
        order: 12,
        slug: 'inspekciya-obektov',
        title: 'Инспекция объектов',
        category: 'ФАСАДЫ · КРЫШИ · ПРОИЗВОДСТВО',
        description: 'Визуальная диагностика труднодоступных конструкций, кровель и фасадов без установки строительных лесов.',
        price: 'от 200 ₾',
        specs: '4K · ДОКУМЕНТАЦИЯ',
        image: '/media/drone-service/object-inspection-from-territory-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-inspekciya-obektov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 9,
        order: 17,
        slug: 'kontrol-territorii',
        title: 'Мониторинг территорий',
        category: 'ЛАНДШАФТ · КАРЬЕРЫ · ПЕРИМЕТР',
        description: 'Крупный объект сложно контролировать с земли. Еженедельный облёт с GPS-привязкой даёт полную карту изменений без выезда на место.',
        price: 'от 200 ₾',
        specs: 'GPS · ОТЧЁТЫ · ЕЖЕНЕДЕЛЬНО',
        image: '/media/drone-service/territory-monitoring-2.png',
        primaryHref: '#contact',
        secondaryHref: '#service-kontrol-territorii',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 10,
        order: 14,
        slug: 'interiery-sklady',
        title: 'Съёмка интерьеров и складов',
        category: 'ШОУРУМЫ · МАГАЗИНЫ · АРЕНДАТОРЫ',
        description: 'Дрон пролетает сквозь стеллажи, проёмы и цеха — туда, куда камера на штативе не попадёт. Один дубль — и пространство читается.',
        price: 'от 200 ₾',
        specs: 'FPV · ПЛАНИРОВКА',
        image: '/media/drone-service/interiors-warehouses-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-interiery-sklady',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 11,
        order: 16,
        slug: 'sport-kompleksy',
        title: 'Спорт комплексы',
        category: 'СТАДИОНЫ · АРЕНЫ · ТЕННИСНЫЕ КОРТЫ',
        description: 'Арена выглядит масштабно только с воздуха. Снимаем поля, трибуны и инфраструктуру — для сайта, инвесторов и соцсетей.',
        price: 'от 200 ₾',
        specs: '4K · 60FPS · ОБЛЁТ',
        image: '/media/drone-service/sport-complex-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-sport-kompleksy',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 12,
        order: 7,
        slug: 'reklama-brand-video',
        title: 'Реклама и бренд видео',
        category: 'БРЕНДЫ · КОРПОРАТИВЫ · ПРОДУКТЫ',
        description: 'Воздушные кадры, сценарий и монтаж в одном проекте. Видео, которое работает в рекламе, на сайте и в соцсетях.',
        price: 'от 200 ₾',
        specs: '4K · ПРОМО · МОНТАЖ',
        image: '/media/drone-service/brand-video-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-reklama-brand-video',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 13,
        order: 8,
        slug: 'aerosyemka-dlya-avto-i-avtosalonov',
        title: 'Автосалоны и шоурумы',
        category: 'АВТОПЛОЩАДКИ · ДИЛЕРЫ · СЕТИ',
        description: 'Покупатель выбирает глазами. Показываем весь ассортимент, площадку и инфраструктуру салона одним пролётом.',
        price: 'от 200 ₾',
        specs: '4K · ПРОДАЖИ · АВТО',
        image: '/media/drone-service/auto-showroom-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-aerosyemka-dlya-avto-i-avtosalonov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 14,
        order: 18,
        slug: 'agro-i-vinodelie',
        title: 'Агро и виноделие',
        category: 'БРЕНДЫ · ИНВЕСТОРЫ · ПРОИЗВОДИТЕЛИ',
        description: 'Грузинское вино начинается с лозы. Аэросъёмка виноградников и хозяйств — для мониторинга урожая и промо бренда.',
        price: 'от 200 ₾',
        specs: 'АНАЛИТИКА · АГРОБИЗНЕС',
        image: '/media/drone-service/agro-wine-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-agro-i-vinodelie',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 15,
        order: 6,
        slug: 'zemelnye-uchastki',
        title: 'Земельные участки',
        category: 'ЗАСТРОЙЩИКИ · ДЕВЕЛОПЕРЫ · ИНВЕСТОРЫ',
        description: 'Границы, рельеф, окружение и доступность — всё в одном облёте. Продаёт быстрее любого описания.',
        price: 'от 200 ₾',
        specs: 'ОЦЕНКА · ПАНОРАМА',
        image: '/media/drone-service/territory-monitoring-2.png',
        primaryHref: '#contact',
        secondaryHref: '#service-zemelnye-uchastki',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 17,
        order: 9,
        slug: 'inspekciya-fasadov',
        title: 'Инспекция фасадов',
        category: 'ЭКСПЛУАТАЦИЯ · ИНЖЕНЕРЫ · ПАНЕЛИ',
        description: 'Полный облёт фасада с видео — без лесов, без риска для персонала и без остановки объекта. Материал передаётся вашим специалистам.',
        price: 'от 200 ₾',
        specs: 'ДИАГНОСТИКА · ШВЫ',
        image: '/media/drone-service/drone-facade-2.png',
        primaryHref: '#contact',
        secondaryHref: '#service-inspekciya-fasadov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 18,
        order: 15,
        slug: 'inspekciya-solnechnyh-paneley',
        title: 'Инспекция солнечных панелей',
        category: 'ЭНЕРГЕТИКИ · ОПЕРАТОРЫ · ИНВЕСТОРЫ',
        description: 'Грязь и повреждения снижают выработку панелей до 30%. Один облёт с видео — и у вашего инженера есть полная картина без подъёма на крышу.',
        price: 'от 200 ₾',
        specs: 'КОНТРОЛЬ · ЭФФЕКТИВНОСТЬ',
        image: '/media/drone-service/roof-inspection-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-inspekciya-solnechnyh-paneley',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 19,
        order: 5,
        slug: 'regulyarnye-aerootchety',
        title: 'Регулярные аэроотчёты',
        category: 'БАНКИ · ИНВЕСТОРЫ · УПРАВЛЯЮЩИЕ',
        description: 'Еженедельные облёты с GPS-отчётом — инвестор видит динамику объекта без выезда на стройку.',
        price: 'от 200 ₾',
        specs: '4K · GPS · ПРОГРЕСС',
        image: '/media/drone-service/reporting-1.png',
        primaryHref: '#contact',
        secondaryHref: '#service-regulyarnye-aerootchety',
        secondaryCtaLabel: 'На странице',
    },
];
