export type DroneServiceItem = {
    id: number;
    order: number;
    slug: string;
    title: string;
    category: string;
    description: string;
    price: string;
    image: string;
    primaryHref: string;
    primaryCtaLabel?: string;
    secondaryHref?: string;
    secondaryCtaLabel?: string;
    tag?: string;
    featured?: boolean;
};

export const droneServiceItems: DroneServiceItem[] = [
    {
        id: 1,
        order: 1,
        slug: 'nedvizhimost',
        title: 'Недвижимость',
        category: 'Риелторы · Застройщики · Инвесторы',
        description: 'Аэрофото и видео для листингов, инвест-презентаций и продаж. Объекты с аэровидео продаются на 68% быстрее.',
        price: '4K · GPS · от 250 ₾',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAslg3OGFik_wYnbSrvZFf4elw662oadBDYTv554Z6v4yr1yZwfUQbYyQPxT5CoE0rdvaBztQs0rmkSum_EeIX4u7LPX6VBpMjuOR7tVaIEjC3hLPTBViLzc31ukhT6Ja3vYCpDvqXuYE9ZJ8Km6t3LF3lF7kfQArPt4P2WneniU6ZZvn03h65yRt3wjHFSQf0FP5w-xpJsLHbN85ebim02aAfQa4Wifzc5nlBf4NoyHYv9SqSlsJIkPN4jDqUXAQPlF-jamVAj_Uh',
        primaryHref: '/drone-real-estate',
        secondaryHref: '#service-nedvizhimost',
        secondaryCtaLabel: 'На странице',
        tag: 'SALE',
    },
    {
        id: 2,
        order: 2,
        slug: 'monitoring-stroiki',
        title: 'Мониторинг стройки',
        category: 'ДЕВЕЛОПЕРЫ · БАНКИ · ПОДРЯДЧИКИ',
        description: 'Еженедельные отчеты для инвесторов и контроль этапов работ с воздуха.',
        price: 'GPS · Orthomap · от 600 ₾/мес',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDL-aaYMqi4OV_lRoC4G9oyP4H6x9FGquVmBIE5Dw1Tjia0VVFnIDM46aqe0vae_yj8-YJTpkUQpXszPfHEcr5BwYIoddfAOr8jDPjy5A4cMq2U0OTidRwiSHyScPIFk8skXgDtDN2bKBFZQKLSq_BhieF8IbqBrnpZCnP2ZYrmBbXS_fdJWDwJ-htcsncXD5pG_gfgoc_WYyVoZpC53lLUmScRZ5PeiiYFEpJcL4cyG7bPffQsDSWX8Z6IupITNVrmyainYBZMfGcZ',
        primaryHref: '/drone-construction-monitoring',
        secondaryHref: '#service-monitoring-stroiki',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 3,
        order: 3,
        slug: 'fpv-semka',
        title: 'FPV Съёмка',
        category: 'ИНТЕРЬЕРЫ · СКЛАДЫ · СПОРТ · АРЕНЫ',
        description: 'Динамичные пролеты сквозь объекты. Реклама и экшн-видео с эффектом присутствия.',
        price: 'High Speed · 4K · от 450 ₾',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5jr5-Vd5EBLnWavSe4YMNrcUbo7RBSE2DOe67LtAhVFf29H-CjbJhM8konQuitIcT4rzszP22xqh_dAlLXhVDWkdBBpIRVF0Qm6Y9Prb9XgbgSO5KszKfaCbxH0Z_7i5wPdJ0XEc9Xxwq0v4A2Pu2Aug6tZHPwkQivcbvnodEw8oLJLkkRkb8kKK-g9uZgVqCTqWkxxCB6oP3hborIRuj7vYSLxgbGjs7v7UW2pgv5o36QZkoPwZmjjaHPs7zhBGJPs4XD06NxvV6',
        primaryHref: '/drone-fpv-cinema',
        secondaryHref: '#service-fpv-semka',
        secondaryCtaLabel: 'На странице',
        tag: 'HOT',
        featured: true,
    },
    {
        id: 4,
        order: 4,
        slug: 'oteli-kurorty',
        title: 'Отели & Курорты',
        category: 'ОТЕЛИ · АПАРТ-ОТЕЛИ · КУРОРТЫ',
        description: 'Атмосферные промо-ролики для Booking и социальных сетей вашего бизнеса.',
        price: 'Lifestyle · 360° · от 350 ₾',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo2itZXdS9Xvd94BVODnsRMnJiTzcqdD7b2iewCouIlOM_K2v2oX4kcY1_VfZ0L34cZKAlG_7uqMVqDSRxkJ7Qo-Yha0eIGm43-jm4-bAv4Qp5fMA07hLoZjcZaG8kKcV6R8UMU1EIA_ZsxLzSiOqY6VXQFQNoAARd1D3qAqYUGGpPLO-neNlsdVSs0JTO3ENd8nlUg8saD2OU9xyTAPC-dKmNY9f4qI1lecJlXhGqO0U8XcmDFD9hJKqQYiP4MXRbyiBsEXGsqDjy',
        primaryHref: '/drone-hotels-tourism',
        secondaryHref: '#service-oteli-kurorty',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 5,
        order: 5,
        slug: 'restorany',
        title: 'Рестораны',
        category: 'ВЕРАНДЫ · ЛОКАЦИИ · АТМОСФЕРА',
        description: 'Верандный ресторан теряет гостей — снаружи не видно. Аэросъёмка террасы.',
        price: '4K · Reels · Stories',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBVx3BuByNqzEGkk_UvdHwzOz94ObjfA9aBtc9mqzbaJZHvhU73IBBfyMgww71Q43jZKhaL_jgHKc-kH_9AM0v0olAZBRiJGdA7zShjXQ9cRfENOM39effzhfpGvLq5HgTYqopjTB5MZ29VK6EVzGmsCgSjOb_olsWMKu7dIE-jXccq3c7X7Rkl58IzCryq-1qrN8ipd6LJVizMoZO9UMT13jVGJ5bqpOFJoddMhJrLcIPQJJsXIQKIl6xFymX_EzPYIorwpGVLKh9g',
        primaryHref: '/drone-services/drone-restaurants',
        secondaryHref: '#service-restorany',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 6,
        order: 6,
        slug: 'turizm',
        title: 'Туризм и локации',
        category: 'ПРИРОДА · МАРШРУТЫ · ГЛЭМПИНГИ',
        description: 'Горы и замки Грузии не продашь текстом — только видом с воздуха. Cinematic аэросъёмка.',
        price: '4K · Cinematic · Music',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgmImkuYQv-P5A9gQZbktMdvmOTHgj7uMKWyfvzDb1y0DVzxTp-VJpb79lKXoa_jPq8LzY1VFT_EeSrHNvR7Vb-c-WNEWeyvcJ_yu3MGQCDxX2XUKw-QwQ92aaKoxY_Ey7VMKblCicB0RUMEHrA_CsjmafaL4dZ6A3bdztSdq7QjzxB87wLC1WGtvkizcoDZ4zjbIbwESW39CqgHcZckSvDu-cJPGjnqrzmwMCiPJ55nV3A90l7BisyuZKew2CYH6jQu5fz8-bwT_I',
        primaryHref: '/drone-hotels-tourism',
        secondaryHref: '#service-turizm',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 7,
        order: 7,
        slug: 'meropriyatiya',
        title: 'Мероприятия',
        category: 'ИВЕНТЫ · ОТКРЫТИЯ · СПОРТ',
        description: 'С земли — толпа. С воздуха — масштаб и атмосфера. Монтаж за 48 часов.',
        price: '4K · Multicam · Reels',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPLTjhVnWq4EWExthggb3xu2g-ihnoCIxuCEDPEjzb63aOWiQY7DIkh8wGwj-hF3ubgtQqZuyf0YQ3m-2qyddZMyff9ao61XDRN9QyjFu53sSBOqLZy5TbDZ05YQm-5Ob9lpiGiSRJPoIJOAclJEY4olc1JnZn0RVcKs3YM8DEADBxMx98nLtn4YIdy4bRrlFVKwY_xLr7BFXy0SaDWP6TGsJU9Q21Z3aPA2zaXQyXJY8yn893sOOnvkxADEHBCa8MwSmAUasW1jYu',
        primaryHref: '/drone-weddings-events',
        secondaryHref: '#service-meropriyatiya',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 8,
        order: 8,
        slug: 'inspekciya-obektov',
        title: 'Инспекция объектов',
        category: 'ФАСАДЫ · КРЫШИ · ПРОМЗДАНИЯ',
        description: 'Дрон осматривает здание за 40 минут. Безопасно и точно.',
        price: 'Hi-Res · PDF-акт · Annotations',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuANIoX83hfhNBGz1gGl0aBAGAE7Rl3qSAHirYm8KS8LQcbX_eLHeFYU2jhgeUdHX1XN6QVzevWxLwypi0V7lWsAKOkKYi_Qd7nh58mM5PfziCofpR8Jcl2z7eDkow1-0GxLckvFM8vlWoIZ0TCYOv1PMvL77q0PrBaxLRuomdHWSsnnWwI3tZYEymAUUQqmtYKshRNjJqo4koRCQU0iPI8MXEAI1QZ6oYqBgkcLeaCruAO_-H7t2iTArtbwAZ3yLuZYKWIXMOP2rsZL',
        primaryHref: '/drone-object-inspection',
        secondaryHref: '#service-inspekciya-obektov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 9,
        order: 9,
        slug: 'kontrol-territorii',
        title: 'Мониторинг территорий',
        category: 'ПОСЕЛКИ · ПАРКИ · КАРЬЕРЫ',
        description: 'Еженедельные облёты с GPS-привязкой. Идеально для крупных объектов и планирования ландшафта.',
        price: '4K · GPS · Report',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJh8bHnpidCNuwFQbIFyTNeIqyh-wMO04mxfRJzPVkdCEfHFormf7nJQAE_yAr7lFN28uNLECuiax2B_ibvwS_Pa13K8SLJO0g04oFZiwjeOuv58qVgHp8XSD7TyWJc4kVQBC3qqFTQolLNZKayW8WV7elIrgInZ3KWW3nO7Rf62fdb6BK2uutrwK6xe_0Xb_wfGwlyG2dOgRmPqb4XFbJ-Xgva6JxQCwIAddhy0_Hcn0na_Cam1OfoS9HN97jq6GyFTIBq--2OwW1',
        primaryHref: '/drone-services/drone-territory',
        secondaryHref: '#service-kontrol-territorii',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 10,
        order: 10,
        slug: 'interiery-sklady',
        title: 'Съёмка интерьеров и складов',
        category: 'СКЛАДЫ · ШОУРУМЫ · ЦЕХА',
        description: 'Пролеты сквозь узкие проемы и стеллажи. Идеально для складов, шоурумов и производства.',
        price: '4K · FPV · WOW-effect',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDZajCdckNMjVgU9jxM8FpPxVHg7u9BZavVfsuS33_i0AdKrhinM0G77BgaQjD9NKqXUPsEECz42Bjezta4a7XddNhK_pZBTS1f7Lns1h6eeXYqrXJg5easP_Z3OAQb2PK-mYtoUYXFJL-4ME9_o3GM-3VmuCWB-Vx4XaT0nALmtf6P4bYu0l4Vhs7CTDLiGrLRRew5D7YHWKqhFr2L66sqVyNlT46nvSsSsp7t8yW4mHZvRZVhuKib39ou8Fvjjqvkr5reB41FA-p2',
        primaryHref: '/drone-warehouses',
        secondaryHref: '#service-interiery-sklady',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 11,
        order: 11,
        slug: 'sport-kompleksy',
        title: 'Спорт комплексы',
        category: 'ПОЛЯ · АРЕНЫ · ТЕННИСНЫЕ КОРТЫ',
        description: 'Масштабные планы футбольных полей и арен. Динамика и драйв для вашего спортивного объекта.',
        price: '4K · 60fps · Dynamic',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnuksVWeufIQzdLEth75uzPMH5yDohIX_DakkzV8oz3cfD70qhpXYZ-iqXKxRE-5tM8qQCwiFWzBkYSUFwHtpDCHVE0JQTo2fAfNWuZt_HpOOiUFlnYDD7A5vbruVqhQUv7p69FrxIIqasL5h9c3ZEFwvUZNepVMiXMpCWFNXf-HTeEBGnBlBLk-Emh3U8fQmSaJ6n0lNy1EnElk1WY5quKiA4Z-1strCBn4LoSKZaJzHZOWqIGzTZJqPcihmJ9a506PGpvBL7upwV',
        primaryHref: '/drone-services/drone-sport',
        secondaryHref: '#service-sport-kompleksy',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 12,
        order: 12,
        slug: 'reklama-brand-video',
        title: 'Реклама и бренд видео',
        category: 'БРЕНДЫ · КОРПОРАТИВЫ · ПРОДУКТЫ',
        description: 'Сценарий, съёмка и монтаж. Воздушные кадры, которые продают ваш бренд и ценности.',
        price: '4K · Script · Editing',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD62ozYM1NmVtaO9kCAbv0pwHC2OX_-OjjDgYwBtfzr8VjMszaA9isTBLH5zvdEfO2csz9IV3mZvh8H6sWQJcQiPd9yGJDVpr5gJmXZGX9NrmxVS0FMHe0D0OxBzhA2C-lJwUHJJnJphgrrl1sAdNm6SM52Dp1JvBFXfxEayNUfQCIZwVvEIrxKLmMffaw8njHG7Hlc9Px7jxD7zX1Nl-U8a_Q-dBKGjgsZHhAVtauYxxwpoixaGrqn_VGk7CT7omYWrijC2kzSP7Fc',
        primaryHref: '/drone-services/drone-brand-video',
        secondaryHref: '#service-reklama-brand-video',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 13,
        order: 13,
        slug: 'aerosyemka-dlya-avto-i-avtosalonov',
        title: 'Аэросьемка для авто и автосалонов',
        category: 'АВТО · АВТОСАЛОНЫ · АВТОПЛОЩАДКИ',
        description: 'Показываем масштаб площадки, ассортимент автомобилей и инфраструктуру в одном пролёте.',
        price: 'Drone · от 400 ₾',
        image: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=1200&q=80',
        primaryHref: '/drone-services/drone-auto',
        secondaryHref: '#service-aerosyemka-dlya-avto-i-avtosalonov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 14,
        order: 14,
        slug: 'agro-i-vinodelie',
        title: 'Агро и виноделие',
        category: 'ВИНОГРАДНИКИ · САДЫ · ВИНОДЕЛЬНИ',
        description: 'Мониторинг участков, съёмка хозяйств и промо виноделен с воздуха.',
        price: '4K · AGRO · MONITORING',
        image: 'https://images.unsplash.com/photo-1470158499416-75be9aa0c4db?w=1200&q=80',
        primaryHref: '/drone-services/drone-wine',
        secondaryHref: '#service-agro-i-vinodelie',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 15,
        order: 15,
        slug: 'zemelnye-uchastki',
        title: 'Земельные участки',
        category: 'УЧАСТКИ · РЕЛЬЕФ · ПОДЪЕЗДЫ',
        description: 'Показываем границы, окружение, рельеф и доступность участка с воздуха.',
        price: '4K · LAND · OVERVIEW',
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
        primaryHref: '/drone-services/drone-land-sale',
        secondaryHref: '#service-zemelnye-uchastki',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 16,
        order: 16,
        slug: 'inspekciya-krysh',
        title: 'Инспекция крыш',
        category: 'КРОВЛЯ · ДЕФЕКТЫ · ДОСТУП',
        description: 'Быстрый осмотр кровли, покрытий и труднодоступных зон без подъёмной техники.',
        price: '4K · ROOF · INSPECTION',
        image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=1200&q=80',
        primaryHref: '/drone-services/drone-facade',
        secondaryHref: '#service-inspekciya-krysh',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 17,
        order: 17,
        slug: 'inspekciya-fasadov',
        title: 'Инспекция фасадов',
        category: 'ФАСАДЫ · ШВЫ · ВЫСОТА',
        description: 'Визуальная проверка фасадов, стыков и внешних дефектов на высоте.',
        price: '4K · FACADE · INSPECTION',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80',
        primaryHref: '/drone-services/drone-facade',
        secondaryHref: '#service-inspekciya-fasadov',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 18,
        order: 18,
        slug: 'inspekciya-solnechnyh-paneley',
        title: 'Инспекция солнечных панелей',
        category: 'SOLAR · КРЫШИ · ОСМОТР',
        description: 'Визуальный контроль солнечных панелей и rooftop-установок с воздуха.',
        price: '4K · SOLAR · ROOFTOP',
        image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80',
        primaryHref: '/drone-services/drone-solar',
        secondaryHref: '#service-inspekciya-solnechnyh-paneley',
        secondaryCtaLabel: 'На странице',
    },
    {
        id: 19,
        order: 19,
        slug: 'regulyarnye-aerootchety',
        title: 'Регулярные аэроотчёты',
        category: 'ОТЧЁТЫ · ДИНАМИКА · КОНТРОЛЬ',
        description: 'Повторные облёты по графику для фиксации изменений и состояния объекта.',
        price: '4K · REPORTS · GPS',
        image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1200&q=80',
        primaryHref: '/drone-services/drone-reporting',
        secondaryHref: '#service-regulyarnye-aerootchety',
        secondaryCtaLabel: 'На странице',
    },
];
