import aiRealEstateImage from "@/services-images/ai-real-estate/final/1.png";
import tourRealEstateImage from "@/services-images/360-real-estate+/final/1.png";
import droneRealEstateImage from "@/services-images/drone-real-estate/final/1.png";
import reelsRealEstateImage from "@/services-images/reels-realtor/final/1.png";

export type ChooserTab = "services" | "industries";

export type SubServiceItem = {
    id: string;
    title: string;
    titleEn: string;
    price: string;
    priceEn: string;
    hasL3: boolean;
    href: string; // L3 link or #contact
    image: string;
    tag: string;
    tagEn: string;
    desc: string;
    descEn: string;
};

export type DirectionItem = {
    key: string;
    title: string;
    titleEn: string;
    icon: string;
    startingPrice: string;
    startingPriceEn: string;
    badge: string;
    badgeEn: string;
    flagshipHref: string;
    flagshipTitle: string;
    flagshipTitleEn: string;
    flagshipDesc: string;
    flagshipDescEn: string;
    image: string;
    readyCount: number;
    items: SubServiceItem[];
};

export const SERVICES_DATA: DirectionItem[] = [
    {
        key: "aerial",
        title: "Аэросъёмка",
        titleEn: "Aerial Filming",
        icon: "✈️",
        startingPrice: "от 250 ₾",
        startingPriceEn: "from 250 ₾",
        badge: "4 страницы L3",
        badgeEn: "4 L3 pages",
        readyCount: 4,
        flagshipHref: "/drone-services/drone-real-estate",
        flagshipTitle: "Аэросъёмка недвижимости и ЖК",
        flagshipTitleEn: "Aerial Real Estate & Dev",
        flagshipDesc: "4K HDR съёмка масштаба, локации и окружения для девелоперов и агентств",
        flagshipDescEn: "4K HDR aerial capture of location, infrastructure & scale",
        image: droneRealEstateImage.src,
        items: [
            {
                id: "drone-re",
                title: "Недвижимость и ЖК",
                titleEn: "Real Estate & Dev",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: true,
                href: "/drone-services/drone-real-estate",
                image: droneRealEstateImage.src,
                tag: "4K HDR / FPV",
                tagEn: "4K HDR / FPV",
                desc: "Локация, масштаб ЖК и окружение одним планом",
                descEn: "Location, development scale & surroundings in one take",
            },
            {
                id: "drone-hotels",
                title: "Отели и курорты",
                titleEn: "Hotels & Resorts",
                price: "от 500 ₾",
                priceEn: "from 500 ₾",
                hasL3: true,
                href: "/drone-hotels-tourism",
                image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80",
                tag: "Кинематография",
                tagEn: "Cinematic",
                desc: "Панорама территории, горы, бассейны и виды из номеров",
                descEn: "Resort panorama, mountains, pools and views",
            },
            {
                id: "drone-restaurants",
                title: "Рестораны и террасы",
                titleEn: "Restaurants & Venues",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: true,
                href: "/drone-services/drone-restaurants",
                image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
                tag: "FPV пролёты",
                tagEn: "FPV Flythrough",
                desc: "Пролёты с улицы через зал на открытую террасу",
                descEn: "Fly-ins from outside into indoor dining & terrace",
            },
            {
                id: "drone-construction",
                title: "Мониторинг стройки",
                titleEn: "Construction Audit",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: true,
                href: "/drone-construction-monitoring",
                image: "https://images.unsplash.com/photo-1541888946425-d0fbb186156f?w=800&auto=format&fit=crop&q=80",
                tag: "B2B отчёты",
                tagEn: "B2B Reports",
                desc: "Регулярная ортофотосъёмка динамики для инвесторов",
                descEn: "Regular progress capture and aerial inspection",
            },
            {
                id: "drone-auto",
                title: "Автобизнес в движении",
                titleEn: "Automotive in Motion",
                price: "от 300 ₾",
                priceEn: "from 300 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80",
                tag: "Динамичный трекинг",
                tagEn: "High-speed Tracking",
                desc: "Слежение за автомобилями на горных серпантинах",
                descEn: "Dynamic chase-cam on winding roads",
            },
            {
                id: "drone-facades",
                title: "Инспекция фасадов и крыш",
                titleEn: "Facade & Roof Audit",
                price: "от 400 ₾",
                priceEn: "from 400 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80",
                tag: "High-res дефектовка",
                tagEn: "High-res Audit",
                desc: "Детальная фотофиксация высотных конструкций",
                descEn: "Detailed inspection of high-rise structures",
            },
        ],
    },
    {
        key: "tour360",
        title: "360° туры",
        titleEn: "360° Virtual Tours",
        icon: "🔄",
        startingPrice: "от 250 ₾",
        startingPriceEn: "from 250 ₾",
        badge: "2 страницы L3",
        badgeEn: "2 L3 pages",
        readyCount: 2,
        flagshipHref: "/360-tour-real-estate",
        flagshipTitle: "360° туры недвижимости и ЖК",
        flagshipTitleEn: "360° Tours for Real Estate",
        flagshipDesc: "Интерактивные 8K панорамы с интеграцией в Google Street View и сайт застройщика",
        flagshipDescEn: "Interactive 8K walkthroughs integrated with Google Street View & web",
        image: tourRealEstateImage.src,
        items: [
            {
                id: "tour-re",
                title: "Недвижимость и апартаменты",
                titleEn: "Real Estate & Living",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: true,
                href: "/360-tour-real-estate",
                image: tourRealEstateImage.src,
                tag: "8K HDR",
                tagEn: "8K HDR",
                desc: "Удалённый показ планировок покупателям из любой точки мира",
                descEn: "Remote spatial walk for buyers worldwide",
            },
            {
                id: "tour-hotels",
                title: "Отели и бутик-виллы",
                titleEn: "Hotels & Boutique Villas",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: true,
                href: "/360-tour-hotels",
                image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80",
                tag: "Google Maps Ready",
                tagEn: "Google Maps Ready",
                desc: "Полное погружение в номера, спа-зоны и рестораны отеля",
                descEn: "Full immersion into rooms, spa areas and hotel venues",
            },
            {
                id: "tour-restaurants",
                title: "Рестораны и банкетные залы",
                titleEn: "Restaurants & Event Halls",
                price: "от 300 ₾",
                priceEn: "from 300 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&auto=format&fit=crop&q=80",
                tag: "Выбор столика",
                tagEn: "Table Selection",
                desc: "Бронирование столов и аренда залов с обзором на 360°",
                descEn: "Virtual table reservation and event booking",
            },
            {
                id: "tour-clinics",
                title: "Медицинские центры и клиники",
                titleEn: "Clinics & Medical Centers",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80",
                tag: "Доверие пациентов",
                tagEn: "Patient Trust",
                desc: "Демонстрация чистоты кабинетов и премиального оборудования",
                descEn: "Showcasing clinical cleanliness and modern tech",
            },
        ],
    },
    {
        key: "reels",
        title: "Reels & Promo",
        titleEn: "Reels & Video",
        icon: "🎬",
        startingPrice: "от 200 ₾",
        startingPriceEn: "from 200 ₾",
        badge: "2 страницы L3",
        badgeEn: "2 L3 pages",
        readyCount: 2,
        flagshipHref: "/reels-promo/reels-realtor",
        flagshipTitle: "Reels для риелторов и агентств",
        flagshipTitleEn: "Reels for Realtors & Agencies",
        flagshipDesc: "Динамичные вертикальные обзоры объектов с субтитрами и саунд-дизайном за 24 часа",
        flagshipDescEn: "Dynamic vertical video tours with captions & sound design in 24h",
        image: reelsRealEstateImage.src,
        items: [
            {
                id: "reels-realtor",
                title: "Риелторы и агентства недвижимости",
                titleEn: "Realtors & Real Estate",
                price: "от 200 ₾",
                priceEn: "from 200 ₾",
                hasL3: true,
                href: "/reels-promo/reels-realtor",
                image: reelsRealEstateImage.src,
                tag: "Быстрые лиды",
                tagEn: "Fast Leads",
                desc: "Продающий формат для Instagram и TikTok с ведущим в кадре",
                descEn: "High-converting video format for Instagram & TikTok",
            },
            {
                id: "reels-hotel",
                title: "Отели и загородные виллы",
                titleEn: "Hotels & Country Villas",
                price: "от 300 ₾",
                priceEn: "from 300 ₾",
                hasL3: true,
                href: "/reels-promo/reels-hotel",
                image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                tag: "Атмосферный вайб",
                tagEn: "Aesthetic Vibe",
                desc: "Эстетика отдыха, утро с видом на горы и детали сервиса",
                descEn: "Relaxation aesthetics, mountain views and luxury service",
            },
            {
                id: "reels-restaurant",
                title: "Ресторанный контент и подача",
                titleEn: "Restaurants & Food Reels",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80",
                tag: "Фуд-видео",
                tagEn: "Food Video",
                desc: "Сочные кадры подачи блюд, барного меню и вечерней атмосферы",
                descEn: "Mouth-watering dish plating, cocktails and nightlife",
            },
            {
                id: "reels-business",
                title: "Бизнес и личные бренды",
                titleEn: "Business & Personal Brands",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80",
                tag: "Экспертный контент",
                tagEn: "Expert Content",
                desc: "Интервью, закулисье компании и экспертные советы",
                descEn: "Founder interviews, behind-the-scenes and expertise",
            },
        ],
    },
    {
        key: "aiContent",
        title: "AI-контент",
        titleEn: "AI Content & 3D",
        icon: "🤖",
        startingPrice: "от 150 ₾",
        startingPriceEn: "from 150 ₾",
        badge: "3 страницы L3",
        badgeEn: "3 L3 pages",
        readyCount: 3,
        flagshipHref: "/ai-visual/ai-staging",
        flagshipTitle: "AI Virtual Staging интерьеров",
        flagshipTitleEn: "AI Virtual Staging",
        flagshipDesc: "Виртуальная меблировка пустых квартир и черновой отделки за 12 часов",
        flagshipDescEn: "Virtual furnishing of raw concrete & empty apartments in 12h",
        image: aiRealEstateImage.src,
        items: [
            {
                id: "ai-staging",
                title: "AI Staging интерьеров ЖК",
                titleEn: "AI Virtual Staging",
                price: "от 150 ₾",
                priceEn: "from 150 ₾",
                hasL3: true,
                href: "/ai-visual/ai-staging",
                image: aiRealEstateImage.src,
                tag: "Меблировка в 4K",
                tagEn: "4K Furnishing",
                desc: "Превращение бетона и пустых комнат в дизайнерские апартаменты",
                descEn: "Turn bare concrete into designer luxury apartments",
            },
            {
                id: "ai-hotel-desc",
                title: "AI Описания для отелей и вилл",
                titleEn: "AI Copy for Hotels & Villas",
                price: "от 200 ₾",
                priceEn: "from 200 ₾",
                hasL3: true,
                href: "/ai-content/hotel-ai-descriptions",
                image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&auto=format&fit=crop&q=80",
                tag: "SEO & Booking.com",
                tagEn: "SEO & Booking.com",
                desc: "Многоязычная оптимизация профилей для роста конверсии бронирований",
                descEn: "Multilingual listing optimization for high booking conversion",
            },
            {
                id: "ai-tourism",
                title: "AI Упаковка для туризма",
                titleEn: "AI Travel Route Packaging",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: true,
                href: "/ai-content/tourism-ai-packaging",
                image: "https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=800&auto=format&fit=crop&q=80",
                tag: "Интерактивные гиды",
                tagEn: "Interactive Guides",
                desc: "Генерация аудиогидов, маршрутов и визуальных открыток",
                descEn: "Generative audio tours, itineraries and visual cards",
            },
            {
                id: "ai-brand",
                title: "AI Бренд-визуализации",
                titleEn: "AI Brand Visuals",
                price: "от 200 ₾",
                priceEn: "from 200 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
                tag: "Концепт-арт",
                tagEn: "Concept Art",
                desc: "Фотореалистичные баннеры и рекламные креативы без затрат на аренду студии",
                descEn: "Photorealistic creative banners without studio rent costs",
            },
        ],
    },
];

export const INDUSTRIES_DATA: DirectionItem[] = [
    {
        key: "realEstate",
        title: "Недвижимость",
        titleEn: "Real Estate",
        icon: "🏢",
        startingPrice: "от 250 ₾",
        startingPriceEn: "from 250 ₾",
        badge: "4 формата L3",
        badgeEn: "4 L3 formats",
        readyCount: 4,
        flagshipHref: "/drone-services/drone-real-estate",
        flagshipTitle: "Медиа-комплекс для застройщиков",
        flagshipTitleEn: "Real Estate Visual Suite",
        flagshipDesc: "Аэросъёмка, 360° туры, Reels для риелторов и AI Staging под ключ",
        flagshipDescEn: "Drone aerials, 360° virtual tours, Realtor Reels & AI Staging",
        image: droneRealEstateImage.src,
        items: [
            {
                id: "ind-re-drone",
                title: "Аэросъёмка ЖК и участков",
                titleEn: "Drone Filming for Devs",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: true,
                href: "/drone-services/drone-real-estate",
                image: droneRealEstateImage.src,
                tag: "4K HDR",
                tagEn: "4K HDR",
                desc: "Масштаб комплекса, видовые характеристики и район",
                descEn: "Scale, views and neighbourhood context",
            },
            {
                id: "ind-re-360",
                title: "360° виртуальные туры",
                titleEn: "360° Virtual Tours",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: true,
                href: "/360-tour-real-estate",
                image: tourRealEstateImage.src,
                tag: "Интерактив",
                tagEn: "Interactive",
                desc: "Удалённые показы планировок для иностранных инвесторов",
                descEn: "Remote virtual viewings for overseas buyers",
            },
            {
                id: "ind-re-reels",
                title: "Reels с риелтором в кадре",
                titleEn: "Reels for Realtors",
                price: "от 200 ₾",
                priceEn: "from 200 ₾",
                hasL3: true,
                href: "/reels-promo/reels-realtor",
                image: reelsRealEstateImage.src,
                tag: "Лидогенерация",
                tagEn: "Lead Gen",
                desc: "Продающие обзоры объектов с динамичным монтажом",
                descEn: "Engaging walk-and-talk video walkthroughs",
            },
            {
                id: "ind-re-ai",
                title: "AI Virtual Staging интерьеров",
                titleEn: "AI Virtual Staging",
                price: "от 150 ₾",
                priceEn: "from 150 ₾",
                hasL3: true,
                href: "/ai-visual/ai-staging",
                image: aiRealEstateImage.src,
                tag: "Дизайн в 4K",
                tagEn: "4K Design",
                desc: "Быстрая меблировка бетона для рекламных объявлений",
                descEn: "Fast virtual furnishing of bare concrete",
            },
        ],
    },
    {
        key: "hotels",
        title: "Отели & Виллы",
        titleEn: "Hotels & Villas",
        icon: "🏨",
        startingPrice: "от 300 ₾",
        startingPriceEn: "from 300 ₾",
        badge: "3 формата L3",
        badgeEn: "3 L3 formats",
        readyCount: 3,
        flagshipHref: "/drone-hotels-tourism",
        flagshipTitle: "Визуальная упаковка отелей",
        flagshipTitleEn: "Hotel & Resort Media",
        flagshipDesc: "Аэросъёмка территории, 360° туры по номерам и сочный контент для соцсетей",
        flagshipDescEn: "Cinematic drone overview, 360° room walkthroughs & Reels",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80",
        items: [
            {
                id: "ind-hotel-drone",
                title: "Аэросъёмка отелей и глэмпингов",
                titleEn: "Drone Hotel Tour",
                price: "от 500 ₾",
                priceEn: "from 500 ₾",
                hasL3: true,
                href: "/drone-hotels-tourism",
                image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80",
                tag: "Пейзажи & Территория",
                tagEn: "Scenery & Grounds",
                desc: "Вся инфраструктура отеля на фоне грузинских гор и моря",
                descEn: "Resort amenities against majestic Georgian nature",
            },
            {
                id: "ind-hotel-360",
                title: "360° туры по номерам и SPA",
                titleEn: "360° Room & Spa Tours",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: true,
                href: "/360-tour-hotels",
                image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80",
                tag: "Google Maps",
                tagEn: "Google Maps",
                desc: "Интерактивная карта отеля для роста прямых бронирований",
                descEn: "Interactive property map for higher direct bookings",
            },
            {
                id: "ind-hotel-reels",
                title: "Reels & Shorts об отдыхе",
                titleEn: "Vacation Reels & Shorts",
                price: "от 300 ₾",
                priceEn: "from 300 ₾",
                hasL3: true,
                href: "/reels-promo/reels-hotel",
                image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
                tag: "Вирусный охват",
                tagEn: "Viral Reach",
                desc: "Эмоции, завтраки с видом и уютные вечера у камина",
                descEn: "Breakfasts with mountain views and cozy fireplace moments",
            },
            {
                id: "ind-hotel-ai",
                title: "AI Описания для OTA и букинга",
                titleEn: "AI OTA & Booking Descriptions",
                price: "от 200 ₾",
                priceEn: "from 200 ₾",
                hasL3: true,
                href: "/ai-content/hotel-ai-descriptions",
                image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&auto=format&fit=crop&q=80",
                tag: "SEO Копирайтинг",
                tagEn: "SEO Copywriting",
                desc: "Продающие тексты на 4 языках для Booking и Airbnb",
                descEn: "Multilingual listings tailored for Booking & Airbnb algorithms",
            },
        ],
    },
    {
        key: "restaurants",
        title: "Рестораны & Бары",
        titleEn: "Restaurants & Bars",
        icon: "🍷",
        startingPrice: "от 350 ₾",
        startingPriceEn: "from 350 ₾",
        badge: "1 формат L3",
        badgeEn: "1 L3 format",
        readyCount: 1,
        flagshipHref: "/drone-services/drone-restaurants",
        flagshipTitle: "FPV & Видео для ресторанного бизнеса",
        flagshipTitleEn: "Restaurant FPV & Video",
        flagshipDesc: "Пролёты дрона через зал на террасу, фуд-съёмка и стильные Reels",
        flagshipDescEn: "Drone fly-ins to terrace, delicious food cinematography & Reels",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
        items: [
            {
                id: "ind-rest-drone",
                title: "FPV пролёт ресторана и террасы",
                titleEn: "FPV Restaurant Flythrough",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: true,
                href: "/drone-services/drone-restaurants",
                image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
                tag: "FPV Cinema",
                tagEn: "FPV Cinema",
                desc: "Эффект присутствия гостя: от фасада до столиков",
                descEn: "Guest presence effect: seamless flow from facade to tables",
            },
            {
                id: "ind-rest-reels",
                title: "Reels меню и шеф-повара",
                titleEn: "Menu & Chef Reels",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80",
                tag: "Food & Bar",
                tagEn: "Food & Bar",
                desc: "Трендовые звуки, процесс приготовления и коктейли",
                descEn: "Trendy sounds, kitchen prep and signature cocktails",
            },
            {
                id: "ind-rest-360",
                title: "360° тур залов и бронь столов",
                titleEn: "360° Dining Tour",
                price: "от 300 ₾",
                priceEn: "from 300 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&auto=format&fit=crop&q=80",
                tag: "Панорама",
                tagEn: "Panorama",
                desc: "Виртуальный выбор стола для банкетов и свадеб",
                descEn: "Virtual table selection for banquets and celebrations",
            },
            {
                id: "ind-rest-ai",
                title: "AI Меню и визуальные карточки",
                titleEn: "AI Menu & Delivery Cards",
                price: "от 180 ₾",
                priceEn: "from 180 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80",
                tag: "Wolt / Glovo",
                tagEn: "Wolt / Glovo",
                desc: "Генерация сочных превью блюд для сервисов доставки",
                descEn: "High-converting previews for delivery apps",
            },
        ],
    },
    {
        key: "tourism",
        title: "Туризм & Гиды",
        titleEn: "Tourism & Travel",
        icon: "🏔️",
        startingPrice: "от 250 ₾",
        startingPriceEn: "from 250 ₾",
        badge: "2 формата L3",
        badgeEn: "2 L3 formats",
        readyCount: 2,
        flagshipHref: "/drone-hotels-tourism",
        flagshipTitle: "Медиа для туризма и туроператоров",
        flagshipTitleEn: "Tourism & Travel Content",
        flagshipDesc: "Казбеги, Сванетия, винодельни Кахетии и уникальные локации",
        flagshipDescEn: "Kazbegi, Svaneti, Kakheti wineries and breathtaking Georgian nature",
        image: "https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=800&auto=format&fit=crop&q=80",
        items: [
            {
                id: "ind-tour-drone",
                title: "Аэросъёмка туров и горных маршрутов",
                titleEn: "Drone Tours & Scenic Routes",
                price: "от 500 ₾",
                priceEn: "from 500 ₾",
                hasL3: true,
                href: "/drone-hotels-tourism",
                image: "https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=800&auto=format&fit=crop&q=80",
                tag: "Эпичные горы",
                tagEn: "Epic Mountains",
                desc: "Кинематографичные пролёты над каньонами и перевалами",
                descEn: "Cinematic flyovers over gorges and mountain passes",
            },
            {
                id: "ind-tour-ai",
                title: "AI Интерактивные маршруты и гиды",
                titleEn: "AI Travel Guides & Audio",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: true,
                href: "/ai-content/tourism-ai-packaging",
                image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
                tag: "AI Packaging",
                tagEn: "AI Packaging",
                desc: "Генерация цифровых путеводителей и брендинг экскурсий",
                descEn: "Digital guides, audio walkthroughs and route branding",
            },
            {
                id: "ind-tour-360",
                title: "360° панорамы достопримечательностей",
                titleEn: "360° Landmark Panoramas",
                price: "от 300 ₾",
                priceEn: "from 300 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800&auto=format&fit=crop&q=80",
                tag: "Google Maps",
                tagEn: "Google Maps",
                desc: "Публикация панорам исторических крепостей и храмов",
                descEn: "Publishing 360° panoramas of historic castles & viewpoints",
            },
            {
                id: "ind-tour-reels",
                title: "Reels тревел-впечатлений",
                titleEn: "Travel Impressions Reels",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80",
                tag: "Вайб Грузии",
                tagEn: "Georgian Vibe",
                desc: "Яркие эмоции туристов и моменты грузинского гостеприимства",
                descEn: "High-energy reels highlighting real traveler emotions",
            },
        ],
    },
    {
        key: "auto",
        title: "Автобизнес & Детейлинг",
        titleEn: "Automotive & Detailing",
        icon: "🏎️",
        startingPrice: "от 250 ₾",
        startingPriceEn: "from 250 ₾",
        badge: "0 страниц L3",
        badgeEn: "Custom quotes",
        readyCount: 0,
        flagshipHref: "#contact",
        flagshipTitle: "Медиа для автосалонов и детейлинга",
        flagshipTitleEn: "Automotive Media Production",
        flagshipDesc: "Динамичные трекинг-съёмки, 360° обзор салонов и продающие Reels",
        flagshipDescEn: "Dynamic car chases, 360° interior scans & sales Reels",
        image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80",
        items: [
            {
                id: "ind-auto-reels",
                title: "Reels тест-драйвов и детейлинга",
                titleEn: "Test-Drive & Detailing Reels",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80",
                tag: "ASMR & Speed",
                tagEn: "ASMR & Speed",
                desc: "Процесс полировки, звук выхлопа и динамика разгона",
                descEn: "Polishing ASMR, exhaust notes and high-speed car aesthetics",
            },
            {
                id: "ind-auto-360",
                title: "360° панорамы автосалонов и шоурумов",
                titleEn: "360° Showroom Scans",
                price: "от 300 ₾",
                priceEn: "from 300 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=80",
                tag: "Виртуальный шоурум",
                tagEn: "Virtual Showroom",
                desc: "Обзор модельного ряда в дилерском центре",
                descEn: "Interactive walk through dealership fleet",
            },
            {
                id: "ind-auto-drone",
                title: "Аэросъёмка автоколонн и треков",
                titleEn: "Drone Car Chases",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&auto=format&fit=crop&q=80",
                tag: "FPV Chase",
                tagEn: "FPV Chase",
                desc: "Следование за машиной на высокой скорости",
                descEn: "High-speed pursuit shots with FPV drone",
            },
            {
                id: "ind-auto-ai",
                title: "AI Студийный фон для автокаталогов",
                titleEn: "AI Studio Showcases",
                price: "от 180 ₾",
                priceEn: "from 180 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80",
                tag: "AI Студия",
                tagEn: "AI Studio",
                desc: "Замена уличного фона на премиальную фотостудию",
                descEn: "Background replacement with high-end luxury studio",
            },
        ],
    },
    {
        key: "clinics",
        title: "Клиники & Медицина",
        titleEn: "Clinics & Medical",
        icon: "🏥",
        startingPrice: "от 300 ₾",
        startingPriceEn: "from 300 ₾",
        badge: "0 страниц L3",
        badgeEn: "Custom quotes",
        readyCount: 0,
        flagshipHref: "#contact",
        flagshipTitle: "Медиа для медицинских центров",
        flagshipTitleEn: "Medical Media Production",
        flagshipDesc: "360° туры для доверия пациентов, экспертные Reels врачей и промо",
        flagshipDescEn: "360° clinical tours, doctor interview Reels and high-trust promos",
        image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80",
        items: [
            {
                id: "ind-clinic-360",
                title: "360° тур операционных и палат",
                titleEn: "360° Clinic & Ward Tours",
                price: "от 350 ₾",
                priceEn: "from 350 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80",
                tag: "Стерильность",
                tagEn: "Sterility",
                desc: "Виртуальный визит в клинику до первого приёма",
                descEn: "Virtual walkthrough before the first appointment",
            },
            {
                id: "ind-clinic-reels",
                title: "Reels с экспертами-врачами",
                titleEn: "Doctor Expert Reels",
                price: "от 250 ₾",
                priceEn: "from 250 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&auto=format&fit=crop&q=80",
                tag: "Доверие",
                tagEn: "Trust",
                desc: "Ответы на частые вопросы пациентов и развенчание мифов",
                descEn: "Doctor answers to patient questions and health myths",
            },
            {
                id: "ind-clinic-promo",
                title: "Промо-видео клиники и технологий",
                titleEn: "Clinic & Tech Promo Video",
                price: "от 450 ₾",
                priceEn: "from 450 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80",
                tag: "4K Cinema",
                tagEn: "4K Cinema",
                desc: "Имиджевый фильм о команде специалистов и оборудовании",
                descEn: "Brand film showcasing medical team & premium equipment",
            },
            {
                id: "ind-clinic-ai",
                title: "AI Инфографика для пациентов",
                titleEn: "AI Patient Infographics",
                price: "от 180 ₾",
                priceEn: "from 180 ₾",
                hasL3: false,
                href: "#contact",
                image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80",
                tag: "Визуализация",
                tagEn: "Visuals",
                desc: "Понятные схемы процедур и памятки для соцсетей",
                descEn: "Clear procedure guides & social media carousels",
            },
        ],
    },
];
